# Site
repository: alirizvi2008/alirizvi2008.github.io
favicon: images/fav.ico

# Content configuration version
version: 2

# Personal info
name: Ali Rizvi
title: Senior Full Stack Software Engineer
email: alirizvi2008@gmail.com
phone: +66 806600946
# website: www.github.com/alirizvi2008

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: alirizvi2008
github_username:  alirizvi2008
stackoverflow_username: "5176922"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: alirizvi.313
linkedin_username: alirizvi2008
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-7S9QH6DGBK"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-pic.png
about_content: | # this will include new lines to allow paragraphs
  HELLO! I am a Full Stack Developer currently working at Agoda - Booking Holdings Group,
  Bangkok previously worked at Omio - GoEuro, Media.net - Directi group having over 5 years of
  experience primarily in ASP.Net MVC, .Net Core, NodeJs, Java, Scala, GraphQL, Javascript, Typescript, 
  ReactJs, Redux and AngularJs.

  I am passionate about building high-quality, scalable, predictable and high-performance web applications or softwares that improves the lives of those around me. 
  I like to resolve design problems, create smart user interface and developing rich web experiences & web applications

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: agoda 
        link: https://www.agoda.com
        # link_text: Agoda Website
        sub_title: Senior Full Stack Software Engineer<br/><small>Apr 2020 - Present</small>
        caption: Central world, Bangkok
        quote: >
          Working as a senior fullstack developer in a cross-functional Pricing team for frontend department.
        description: | # this will include new lines to allow paragraphs
            Designing and implementing features for the customers, features related to pricing and coupons.
            Working on complex end to end features across the funnel.
            Contributing in maintaining the code quality for frontend. 

      - layout: left
        title: omio - GoEuro
        link: https://www.omio.com
        sub_title: Software Engineer<br/><small>Nov 2019 - Mar 2020</small>
        caption: Berlin
        quote: >
          Worked as a software engineer for the Bookings squad under CX tribe.
        description: | # this will include new lines to allow paragraphs
            Worked on the new express checkout flow, for one click booking.
            Improved the price and fare breakdown with clarity and consistency across the funnel for apps and web.
            Developed features on booking page and post booking emailing systems.

      - layout: left
        title: agoda
        sub_title: ITIC Senior Engineer<br/><small>Feb 2019 - Oct 2019</small><br/>Full Stack Software Engineer<br><small>Nov 2017 - Jan 2019</small>
        caption: Central world, Bangkok
        quote: >
          Joined as a developer in Family team (cross-functional horizontal) and later moved to Flights Booking team as a senior developer.
        description: | # this will include new lines to allow paragraphs
            Worked on both desktop and mobile version of the flights page.
            Implemented booking flow from UI to backend with whitelabel support.
            Worked on the credit card form as a standalone form for the PCI zone.
            Integrated responsive ads on pages.

            Developed features on the mobile and desktop verison of the website.
            Implemented various features related to multi booking, family/business segments of bookings.
            Contributed in department efforts in improving the test coverage and performance optimization.

      - layout: left
        title: media.net
        link: https://www.media.net
        sub_title: Web Developer<br/><small>Jun 2015 - Oct 2017</small>
        caption: Directiplex, Andheri Mumbai
        quote: >
          Joined as a fresher, worked as a web developer for the fullstack web team.
        description: | # this will include new lines to allow paragraphs
            Developed and maintained websites, web apps build in ASP.Net and Angular. 
            Developed standalone product to integrate into other web apps to show rich html banners.
            Developed and maintained an OAuth2 Developer app for our ad inventory product to enable other providers to integrate with our product.
            Researched and implemented an internal tool in MEAN stack to monitor health of redis db.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Mumbai
        caption: June 2011 - June 2015
        sub_title: Bachelor of Engineering in Computer Science
        quote: >
          The University of Mumbai is one of the oldest and premier Universities in India. It was established in 1857 consequent upon “Wood’s Education Dispatch”, and it is one amongst the first three Universities in India.
        description: | # this will include new lines to allow paragraphs
          Specialization - Data structures and Analysis of Algorithms.

          During my time at University I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time in university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *MS-TSEC* committee taking on roles such as *Web Master*.

  - title: Online courses
    layout: text
    content: | # this will include new lines to allow paragraphs
      I like to learn and try new stuffs, I prefer reading books/articles and learning through quality course content taught by experts:
      - [Microservices: Designing Highly Scalable Systems](https://www.udemy.com/certificate/UC-d1408b2f-fd25-4d4f-8aa8-74bc2006798f/)
      - [Advanced Javascript](https://www.udemy.com/certificate/UC-b76ce81c-1cc1-44ff-8d2b-0cda80f85fe2/)
      - [Micro Frontends with React](https://www.udemy.com/certificate/UC-466802e3-0c22-4dc1-83bc-c4ae4c8e69be/)
      - [React JS - Mastering Redux](https://www.udemy.com/certificate/UC-ef0038e4-787b-4aa7-ac11-4a647055214c/)

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 5+ years of experience in ASP.NET MVC, C#, Java, SQL ,CSS, SCSS, webpack,
        Javascript & JS frameworks like AngularJs, ReactJs, Redux, Jquery and Underscore.js/lodash.
      - 2+ years of experience in Java, Docker.
      - 1+ year of experience with Node Js with express framework & handlebars.
      - Extensive experience working in an Agile development environment.
      - Comfortable with tools and CI-CD such as Teamcity, Jenkins, Octopus, TortoiseSVN, GIT.
      - Familiar with databases - MS SQL, Redis, Counchbase.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
